Update IAmNotAJeep_and_Maxximus007_WATCHDOG
Added 10 second sleep if pool was down

diff --git a/IAmNotAJeep_and_Maxximus007_WATCHDOG b/IAmNotAJeep_and_Maxximus007_WATCHDOG
--- a/IAmNotAJeep_and_Maxximus007_WATCHDOG
+++ b/IAmNotAJeep_and_Maxximus007_WATCHDOG
@@ -52,7 +52,10 @@ else
   sleep $SLEEP_TIME
 fi
 
-bash '/home/m1/telegram'
+if [  $PAPAMPI_WTM_AUTO_SWITCH  ==  "NO"  ]
+then
+  bash '/home/m1/telegram'
+fi
 
 THRESHOLD=90
 RESTART=0
@@ -155,13 +158,16 @@ do
         echo "Dual mining, check main server $PING_SERVER:$PING_PORT "  | tee -a $LOG_FILE
         if nc -vzw2 $PING_SERVER $PING_PORT;
         then
-          echo "Dual mining, main pool $PING_SERVER:$PING_PORT is up"
+          echo "Dual mining, main pool $PING_SERVER:$PING_PORT is up" | tee -a $LOG_FILE
           INTERNET_IS_GO=1
-        else
+        fi
+        while ! nc -vzw2 $PING_SERVER $PING_PORT ; do
           echo "WARNING: $(date) - Cant reach main pool, $PING_SERVER:$PING_PORT is DOWN" | tee -a $LOG_FILE $ALERT_LOG_FILE
           INTERNET_IS_GO=0
           RESTART=0
-        fi
+          sleep 10
+        done
+
       else
         CURRENT_COIN=$(head -n 200 /home/m1/1bash | grep COIN= | sed 's/COIN=//' | sed 's/\"//' | sed 's/\"//')
         CURRENT_COIN_POOL=$(echo {$CURRENT_COIN}_POOL |sed 's/{//' | sed 's/}//' )
@@ -169,16 +175,19 @@ do
         CURRENT_COIN_PORT=$(echo {$CURRENT_COIN}_PORT | sed 's/{//' | sed 's/}//')
         PING_SERVER=$( cat /home/m1/1bash | grep $CURRENT_COIN_POOL | grep -o '".*"' | sed 's/"//'| sed 's/"//')
         PING_PORT=$(cat /home/m1/1bash | grep $CURRENT_COIN_PORT | grep -o '".*"' | sed 's/"//' |sed 's/"//')
-        echo "Check mining pool, $PING_SERVER:$PING_PORT "
+        echo "Check mining pool, $PING_SERVER:$PING_PORT "  | tee -a $LOG_FILE
         if nc -vzw2 $PING_SERVER $PING_PORT
         then
           echo "Mining pool up"  | tee -a $LOG_FILE
           INTERNET_IS_GO=1
-        else
+        fi
+        while ! nc -vzw2 $PING_SERVER $PING_PORT ; do
+
           echo "WARNING: $(date) - Cant reach mining pool, $PING_SERVER:$PING_PORT is DOWN"   | tee -a $LOG_FILE $ALERT_LOG_FILE
           INTERNET_IS_GO=0
           RESTART=0
-        fi
+          sleep 10
+        done
       fi
       if [[ $RESTART -gt 4 && $INTERNET_IS_GO == 1 ]]
       then
@@ -195,7 +204,7 @@ do
       echo "WARNING: $(date) - Utilization is too low: restart 3main..." | tee -a $LOG_FILE $ALERT_LOG_FILE
       bash '/home/m1/telegram'
       pkill -e miner
-      # Best to restart oneBash - settings might be adjusted already
+      # Best to restart 3main - settings might be adjusted already
       target=$(ps -ef | awk '$NF~"3main" {print $2}')
       kill $target #| tee -a $LOG_FILE
       echo "" #| tee -a $LOG_FILE
@@ -205,7 +214,7 @@ do
       # Give oneBash time to restart to prevent reboot
       sleep $SLEEP_TIME
     else
-      echo "WARNING: $(date) - Low Utilization Detected: 3main will reinit if there are 6 consecutive failures"
+      echo "WARNING: $(date) - Low Utilization Detected: 3main will reinit if there are $COUNT more consecutive failures"
       echo ""
     fi
   else
